import {ReactElement} from 'react';
import {Container, Navbar, Title} from '@mantine/core';
import Head from 'next/head';

import Layout from 'components/Layout';
import {NextPageWithLayout} from 'pages/_app';

const GamePage: NextPageWithLayout = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container>
				<Title>Test Slug</Title>
			</Container>
		</>
	);
};

GamePage.getLayout = function getLayout(page: ReactElement) {
	return <Layout navbar={<Navbar w={300}>Test Navbar</Navbar>}>{page}</Layout>;
};

export default GamePage;
